version: '3.7'
services:
  backend:
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - "5128:5128"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=techmeet
      - DB_PORT=3306
    command: ./wait-for-db.sh
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=techmeet
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  mobile:
    build:
      context: ./mobile
    volumes:
      - ./mobile:/app
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    command: npx expo start --dev-client
    depends_on:
      - backend
volumes:
  db_data:
