export const MELBOURNE_CITIES = {
  "state": "Victoria",
  "region": "Melbourne",
  "cities": [
    "All",
    "Melbourne",
    "Melbourne CBD",
    "Carlton",
    "Fitzroy",
    "Collingwood",
    "Richmond",
    "South Yarra",
    "St Kilda",
    "Docklands",
    "Brunswick",
    "North Melbourne",
    "Southbank",
    "Footscray",
    "Prahran",
    "Windsor",
    "Port Melbourne",
    "Elwood",
    "Toorak",
    "Hawthorn",
    "Kew",
    "Balwyn",
    "Camberwell",
    "Malvern",
    "Caulfield",
    "Bentleigh",
    "Brighton",
    "Glen Waverley",
    "Box Hill",
    "Burwood",
    "Clayton",
    "Dandenong",
    "Springvale",
    "Frankston",
    "Sunshine",
    "Werribee",
    "Point Cook",
    "Altona",
    "Williamstown",
    "Reservoir",
    "Preston",
    "Heidelberg",
    "Bundoora",
    "Epping",
    "Craigieburn",
    "Thomastown",
    "Lalor"
  ]
}
