"""Add goal and update connection model

Revision ID: 333a600202ed
Revises: 4822869bfd54
Create Date: 2025-07-06 03:00:49.709989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '333a600202ed'
down_revision = '4822869bfd54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connections', schema=None) as batch_op:
        # Guard: Only add columns if they don't exist
        conn = op.get_bind()
        insp = sa.inspect(conn)
        columns = [col['name'] for col in insp.get_columns('connections')]
        if 'job_title' not in columns:
            batch_op.add_column(sa.Column('job_title', sa.String(length=255), nullable=True))
        if 'event_met' not in columns:
            batch_op.add_column(sa.Column('event_met', sa.String(length=255), nullable=True))
        if 'event_date' not in columns:
            batch_op.add_column(sa.Column('event_date', sa.String(length=64), nullable=True))
        if 'notes' not in columns:
            batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        if 'tags' not in columns:
            batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))
        if 'github' not in columns:
            batch_op.add_column(sa.Column('github', sa.String(length=255), nullable=True))
        if 'goal' not in columns:
            batch_op.add_column(sa.Column('goal', sa.String(length=255), nullable=True))
        # Guard: Only drop column if it exists
        if 'company_location' in columns:
            batch_op.drop_column('company_location')
        # Guard: Only alter columns if they exist
        if 'user_id' in columns:
            batch_op.alter_column('user_id', existing_type=mysql.INTEGER(), nullable=False)
        if 'name' in columns:
            batch_op.alter_column('name', existing_type=mysql.VARCHAR(length=120), type_=sa.String(length=255), nullable=False)
        if 'email' in columns:
            batch_op.alter_column('email', existing_type=mysql.VARCHAR(length=120), type_=sa.String(length=255), existing_nullable=True)
        if 'company' in columns:
            batch_op.alter_column('company', existing_type=mysql.VARCHAR(length=120), type_=sa.String(length=255), existing_nullable=True)
        if 'linkedin' in columns:
            batch_op.alter_column('linkedin', existing_type=mysql.VARCHAR(length=120), type_=sa.String(length=255), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_location', mysql.VARCHAR(length=120), nullable=True))
        batch_op.alter_column('linkedin',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('company',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('goal')
        batch_op.drop_column('github')
        batch_op.drop_column('tags')
        batch_op.drop_column('notes')
        batch_op.drop_column('event_date')
        batch_op.drop_column('event_met')
        batch_op.drop_column('job_title')

    # ### end Alembic commands ###
