"""Add profile_photo_url and technical_skills to User and changed bio to description in profile model

Revision ID: 5db4699a4255
Revises: d690eefe04e4
Create Date: 2025-06-26 16:28:54.621570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5db4699a4255'
down_revision = 'd690eefe04e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)

    # Add 'description' and drop 'bio' in profiles if not already present
    profile_columns = [col['name'] for col in inspector.get_columns('profiles')]
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        if 'description' not in profile_columns:
            batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        if 'bio' in profile_columns:
            batch_op.drop_column('bio')

    # Add new columns to users if not already present
    user_columns = [col['name'] for col in inspector.get_columns('users')]
    with op.batch_alter_table('users', schema=None) as batch_op:
        if 'bio' not in user_columns:
            batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        if 'profile_photo_url' not in user_columns:
            batch_op.add_column(sa.Column('profile_photo_url', sa.String(length=255), nullable=True))
        if 'job_title' not in user_columns:
            batch_op.add_column(sa.Column('job_title', sa.String(length=100), nullable=True))
        if 'technical_skills' not in user_columns:
            batch_op.add_column(sa.Column('technical_skills', sa.JSON(), nullable=True))
        # Only alter column if it exists
        if 'first_name' in user_columns:
            batch_op.alter_column('first_name',
                   existing_type=mysql.VARCHAR(length=50),
                   nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('technical_skills')
        batch_op.drop_column('job_title')
        batch_op.drop_column('profile_photo_url')
        batch_op.drop_column('bio')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', mysql.TEXT(), nullable=True))
        batch_op.drop_column('description')

    op.create_table('profile',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_title', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('skills', mysql.JSON(), nullable=True),
    sa.Column('personality', mysql.JSON(), nullable=True),
    sa.Column('bio', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('profile_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('employment_status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
